#!/usr/bin/env python3
import os
from pathlib import Path

def get_file_list():
    """Get list of files to process with their relative paths and syntax highlighting type."""
    files = []

    # GDScript files
    for path in Path("scripts").glob("**/*.gd"):
        files.append((path, "gdscript"))

    # Resource files
    for path in Path("resources").glob("**/*.tres"):
        files.append((path, "ini"))

    # Scene files
    for path in Path("scenes").glob("**/*.tscn"):
        files.append((path, "ini"))

    # Project file
    project_file = Path("project.godot")
    if project_file.exists():
        files.append((project_file, "ini"))

    return files

def main():
    # Ensure Code directory exists
    code_dir = Path("Code")
    code_dir.mkdir(exist_ok=True)

    # Output single markdown file
    output_path = code_dir / "AllProjectFiles.md"

    files = get_file_list()
    # Stable ordering for deterministic output
    files.sort(key=lambda x: str(x[0]).lower())
    print(f"Found {len(files)} files to process into a single markdown file")

    with open(output_path, 'w', encoding='utf-8') as out:
        # Document header
        out.write("# Project Code Export (Single File)\n\n")
        out.write("Generated by Code/copy_to_single_md.py\n\n")

        # Optional: simple table of contents
        out.write("## Table of Contents\n\n")
        for file_path, _ in files:
            rel_path = file_path
            try:
                rel_path = file_path.relative_to(Path.cwd())
            except Exception:
                pass
            rel_str = str(rel_path)
            anchor = "file-" + rel_str.replace("/", "").replace("\\", "").replace(" ", "-")
            out.write(f"- [{rel_str}](#{anchor})\n")
        out.write("\n---\n\n")

        # File sections
        for idx, (file_path, syntax) in enumerate(files, start=1):
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()

                # Section header with anchor-friendly id
                try:
                    rel_path = file_path.relative_to(Path.cwd())
                except Exception:
                    rel_path = file_path
                rel_str = str(rel_path)
                anchor = "file-" + rel_str.replace("/", "").replace("\\", "").replace(" ", "-")
                out.write(f"<a id=\"{anchor}\"></a>\n\n")
                out.write(f"## {rel_str}\n\n")
                out.write(f"<!-- Original: {rel_str} -->\n\n")
                out.write(f"```{syntax}\n")
                out.write(content)
                out.write("\n```\n\n")
                out.write("---\n\n")

                print(f"Added: {rel_path}")
            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    print(f"\nCombined markdown written to {output_path}")

if __name__ == "__main__":
    # Change to project root
    os.chdir(os.path.dirname(os.path.abspath(__file__)) + "/..")
    main()
