# res://scripts/battle/EffectResult.gd
class_name EffectResult
extends RefCounted

## EffectResult is the standard return type for EffectDefinition.execute().
## It encapsulates all outputs from effect execution, enabling CombatSimulator
## to be a thin orchestrator.

# ============================================================================
# COMBAT EVENTS (VCR Log)
# ============================================================================

## CombatEvents generated by this effect. Appended to turn log for VCR playback.
var events: Array[CombatEvent] = []

# ============================================================================
# TRIGGER DATA
# ============================================================================

## UUIDs of units that were damaged. Used to trigger on_hurt.
var damaged_uuids: Array[String] = []

## UUIDs of units that were killed. Used to trigger on_kill.
var killed_uuids: Array[String] = []

## Heal events - each element is {uuid, amount} dict so same unit can trigger multiple times
var healed_events: Array[Dictionary] = []

# ============================================================================
# DTO CLASSES
# ============================================================================

class DamageRequest extends RefCounted:
	var amount: int
	var damage_type: int
	var targets: Array[String]
	var skip_bump: bool
	var cause: StringName
	
	func _init(p_amount: int, p_damage_type: int, p_targets: Array[String], p_skip_bump: bool = false, p_cause: StringName = &"CAUSE_ATTACK"):
		amount = p_amount
		damage_type = p_damage_type
		targets = p_targets
		skip_bump = p_skip_bump
		cause = p_cause

class CascadeRequestItem extends RefCounted:
	var target: String
	var amount: int
	var skip_bump: bool
	
	func _init(p_target: String, p_amount: int, p_skip_bump: bool = false):
		target = p_target
		amount = p_amount
		skip_bump = p_skip_bump

class CascadeRequest extends RefCounted:
	var damage_type: int
	var items: Array[CascadeRequestItem]
	
	func _init(p_damage_type: int, p_items: Array[CascadeRequestItem]):
		damage_type = p_damage_type
		items = p_items

class KamikazeRequest extends RefCounted:
	var source_uuid: String
	var target_uuid: String
	var damage: int
	var damage_type: int
	var dying_max_hp: int
	
	func _init(p_source_uuid: String, p_target_uuid: String, p_damage: int, p_damage_type: int, p_dying_max_hp: int):
		source_uuid = p_source_uuid
		target_uuid = p_target_uuid
		damage = p_damage
		damage_type = p_damage_type
		dying_max_hp = p_dying_max_hp

# ============================================================================
# STATE FLAGS
# ============================================================================

## If true, the effect applied state changes directly (legacy behavior).
## CombatSimulator should NOT apply additional state changes.
var state_applied: bool = false

## If true, skip death checking after this effect (used for sub-effects).
var skip_death_check: bool = false

## Delegated damage data for CombatSimulator to process via EffectHandlers.
## When set, CombatSimulator should call handle_damage_effect with this data.
var damage_request: DamageRequest = null

## Summon request data for CombatSimulator to process via EffectHandlers.
## Format: {summon_unit_id: StringName, holder_uuid: String, holder_location: LocationIdentifier, ...}
var summon_request: Dictionary = {}

## Multiple summon request for boss effects (array of unit summons).
## Format: [{unit_id: StringName}, ...]
var summon_units_request: Array = []

## Team for summon_units_request ("PLAYER" or "ENEMY").
var summon_team: String = ""

## Cascade damage request for AOE effects like Shockwave.
var cascade_request: CascadeRequest = null

## Kamikaze attack request for Death's Bargain on-death effect.
var kamikaze_request: KamikazeRequest = null

## Transform request for Mimic effect.
## Format: {self_uuid: String, target_unit_id: StringName}
var transform_request: Dictionary = {}

# ============================================================================
# HELPERS
# ============================================================================

## Add a combat event to the result.
func add_event(event: CombatEvent) -> void:
	events.append(event)

## Add multiple combat events.
func add_events(new_events: Array[CombatEvent]) -> void:
	events.append_array(new_events)

## Mark a unit as damaged (for on_hurt triggers).
func mark_damaged(uuid: String) -> void:
	if not uuid.is_empty() and not damaged_uuids.has(uuid):
		damaged_uuids.append(uuid)

## Mark a unit as killed (for on_kill triggers).
func mark_killed(uuid: String) -> void:
	if not uuid.is_empty() and not killed_uuids.has(uuid):
		killed_uuids.append(uuid)

## Mark a heal event. Unlike damage/kill, heals should trigger for EACH event (not deduplicated).
func mark_healed(uuid: String, amount: int = 0) -> void:
	if not uuid.is_empty():
		healed_events.append({"uuid": uuid, "amount": amount})

## Create a simple result with a single event.
static func from_event(event: CombatEvent) -> EffectResult:
	var result := EffectResult.new()
	result.add_event(event)
	return result

## Create an empty result (effect did nothing).
static func empty() -> EffectResult:
	return EffectResult.new()
